apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: inspection-agent
  namespace: cattle-inspection-system
spec:
  selector:
    matchLabels:
      name: inspection-agent
  template:
    metadata:
      labels:
        name: inspection-agent
    spec:
      containers:
        - image: dockerrrboy/inspection-agent
          imagePullPolicy: Always
          name: inspection-agent-container
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
          stdin: true
          volumeMounts:
          - mountPath: /inspection
            name: inspection
{{- if .Values.SetDocker }}
          - mountPath: /var/run/docker.sock
            name: docker-socket
{{- end }}
          - mountPath: /opt/inspection
            name: inspection-agent-sh
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      serviceAccount: inspection-agent
      serviceAccountName: inspection-agent
      volumes:
      - hostPath:
          path: /
          type: ""
        name: inspection
{{- if .Values.SetDocker }}
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: docker-socket
{{- end }}
      - configMap:
          defaultMode: 448
          name: inspection-agent-sh
          optional: false
        name: inspection-agent-sh